#!/usr/bin/env bash
set -e

__setEmail(){
  local _opt=""
  if git rev-parse --is-inside-work-tree 2> /dev/null ;then
    _opt="--local"
  else
    _opt="--global"
  fi
  echo "Set Repository Configuration on ${_opt#--}"
  echo "Run Command: git config ${_opt} user.email \"${1}\""

  git config ${_opt} user.email "${1}"
}

__email=$(gh api /user/public_emails \
	--jq '.[].email' | \
	sed -ne '/users.noreply.github.com/p')

echo "Get Private Email: ${__email}"

read -p "Set Commit Address [y/N]" _question

case "${_question,,}" in
	y|yes) __setEmail ${__email};;
	*) ;;
esac
